insert into customer(firstName, lastName, birthdate) VALUES ('user', 'yang', now());
insert into customer(firstName, lastName, birthdate) VALUES ('woojung', 'yang', now());
insert into customer(firstName, lastName, birthdate) VALUES ('youzheng', 'kim', now());
insert into customer(firstName, lastName, birthdate) VALUES ('konglong', 'jin', now());
insert into customer(firstName, lastName, birthdate) VALUES ('gougou', 'park', now());
insert into customer(firstName, lastName, birthdate) VALUES ('mama', 'kim', now());
insert into customer(firstName, lastName, birthdate) VALUES ('baba', 'yang', now());
insert into customer(firstName, lastName, birthdate) VALUES ('jiejie', 'yang', now());
insert into customer(firstName, lastName, birthdate) VALUES ('jinda', 'yang', now());